#!/usr/bin/env node
// Writes THIRD_PARTY_LICENSES.md: licenses of the runtime dependencies bundled in dist/.
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const tree = JSON.parse(execSync('npm ls --omit=dev --all --json', { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }));
const seen = new Map();
function walk(deps) {
  for (const [name, info] of Object.entries(deps ?? {})) {
    if (name.startsWith('@dash/')) {
      walk(info.dependencies);
      continue;
    }
    if (!info.version) continue; // optional peer dependency that is not installed (not bundled)
    const key = `${name}@${info.version}`;
    if (!seen.has(key)) seen.set(key, { name, version: info.version });
    walk(info.dependencies);
  }
}
walk(tree.dependencies);

function licenseText(dir) {
  if (!existsSync(dir)) return '';
  const f = readdirSync(dir).find((x) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(x));
  return f ? readFileSync(join(dir, f), 'utf8').trim() : '';
}

const out = ['# Third-party licenses', '', 'Clawd Base bundles the following runtime dependencies in `dist/` (generated by `scripts/licenses.mjs`).', ''];
for (const { name, version } of [...seen.values()].sort((a, b) => a.name.localeCompare(b.name))) {
  const dir = join(root, 'node_modules', name);
  let license = 'unknown';
  try {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
    license = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type ?? 'unknown';
  } catch {
    /* not hoisted */
  }
  out.push(`## ${name} ${version} — ${license}`, '');
  const text = licenseText(dir);
  if (text) out.push('```', text, '```', '');
}
writeFileSync(join(root, 'THIRD_PARTY_LICENSES.md'), `${out.join('\n')}\n`);
console.log(`THIRD_PARTY_LICENSES.md: ${seen.size} packages`);
